const fs = require('fs')
const [a, b] = fs.readFileSync('/dev/stdin').toString().split(' ')
const A = parseInt(a)
const B = parseInt(b)
console.log(A + B)
console.log(A - B)
console.log(A * B)
console.log(Math.floor(A / B))
console.log(A % B)